### ISSUE TITLE
Every Second Task Scheduling

### ISSUE THREAD

**Issue by adikalon** [spiral/framework#1101]
Планируете ли вы добавить everySecond() метод? Вон, у той же лары давно имеется...

**Comment by roxblnfk** [comment]
Нет, пока не планируем

**Comment by butschster** [comment]
Привет. 

Мы не планируем добавлять метод everySecond() в Scheduler. Часто планировщик используется не из-за необходимости выполнять задачи каждую секунду, а потому что в PHP бывает сложно красиво описать бизнес-логику. Это приводит к ситуации, когда приходится использовать костыли вроде планировщика для очистки данных или других задач.

Мы постепенно уходим от типичных сценариев запуска задач в пользу Temporal, так как он позволяет создавать понятные и надёжные workflows. Temporal решает проблему сложного управления состоянием и зависимостями, делая процесс автоматизации более элегантным и устойчивым, чем решения на базе традиционного планировщика.

---

We don’t plan to add an `everySecond()` method to the Scheduler. Often, a scheduler is used not because tasks actually need to run every second, but because PHP can make it tricky to implement clean business logic. This leads to relying on workarounds like schedulers for tasks like data cleanup or similar operations.

We are gradually moving away from traditional task scheduling in favor of Temporal. Temporal allows us to create clear and reliable workflows that solve the challenges of managing state and dependencies, offering a more elegant and robust approach than relying on a scheduler.
