### ISSUE TITLE
Return 405 status code when HTTP method does not match

### ISSUE THREAD

**Issue by Chi-teck** [spiral/framework#1171]
### Description

If a path exists in the route configuration, the router shouldn’t return a 404 just because the HTTP method isn’t allowed. Instead, it should return a 405 response and include the `Allow` header.

Symfony router and FastRoute support this.

### Code and/or config needed to reproduce the problem. 

Create a route like this
```
[Route(route: '/example', name: 'example', methods: ['POST'])]
```
Send GET request to /example. Note that it returns 404, not 405, and `Allow` header is missing.

| Q                   | A
| ------------------- | ---
| Framework Version   | 3.14
| PHP version         | 8.3
| Operating system    | Linux

**Comment by butschster** [comment]
Hey, @Chi-teck .

Sorry for the long response. I've just checked the Spiral router, and here's what I found.

The current implementation is optimized for performance. The router first checks the HTTP methods when looking for a matching route. If the method doesn't match, it skips the route entirely without evaluating the regex. This avoids unnecessary regex checks for routes that don't match by method.

Changing this behavior to evaluate the regex first and then check the HTTP methods would cause performance issues, especially in projects with many routes.

That said, Spiral allows you to use FastRoute or Symfony Router instead of the default Spiral router component. Both of these support returning a 405 status code with the Allow header. If this functionality is critical for your project, you can replace the router with one of these alternatives. And if you do implement this, feel free to share your solution with the community—it could be helpful for others too!

**Comment by Chi-teck** [comment]
Makes sense. Thank you.
