### ISSUE TITLE
Add ability for config to read from yaml/json-files

### ISSUE THREAD

**Issue by EvgenyBarinov** [spiral/framework#381]
It will be useful if InjectableConfig classes can read config structure from json and yaml files.

For example config can read from php by default ('php'). But if some specific variable with type equals to 'yaml' or 'json' it try to read file in this format from config dir.

**Comment by vladgorenkin** [comment]
DirectoryLoader already tries to load php and json files by checking if config file with associated extension exists. For example if there is no 'database.php' ConfigManager will try to load 'database.json'. You will have to reimplement DirectoryLoader in order to add yaml support which is a problem I referenced here: https://github.com/spiral/framework/issues/364
