### ISSUE TITLE
Roadrunner 2.0 Support

### ISSUE THREAD

**Issue by connerbw** [spiral/framework#395]
## Description

Roadrunner 2.0 was released a few days ago, but this project's `main.go` file is still pointing to `github.com/spiral/roadrunner/cmd/rr/cmd` (and this folder doesn't exist anymore in the [master branch](https://github.com/spiral/roadrunner)?)

## Example

Forgive my ignorance, but to compile my own Go RPC services I've been using:

- https://github.com/spiral/framework/blob/master/main.go

The conventions seem to have changed and I don't understand what do to with the Spiral main.go file anymore, ie.

- https://roadrunner.dev/docs/beep-beep-build
- https://github.com/spiral/roadrunner-binary/blob/master/main.go

So, this feature request is to support roadrunner V2 out-of-the-box and to clarify the docs, example:

+ https://spiral.dev/docs/cookbook-golang-library
  + ("Read more about RoadRunner services here." links to a `beep-beep-service` page that is now 404.)

Thank you for your consideration.

**Comment by SerafimArts** [comment]
In the new мersion of the framework (master aka 2.8), we are preparing support for RR2. Optional, because dependencies of the second RR version requires php 7.4+.

So far, not all plugin functionality is ready (https://github.com/spiral/roadrunner/issues/403), so I'm not ready to provide an exact release date and update installation instructions (i.e. documentation) right now.

However, the current master branch already supports both RR1.9 (`spiral` binary) and RR2 (`rr` binary) in HTTP mode.

It should be noted that in subsequent releases there will no longer be direct dependencies of the framework on the RoadRunner, (including `main.go`), however, it will remain as the recommended application server for the framework and many optional components will use this particular implementation.
