### ISSUE TITLE
Shouldn't NativeAttributeReader::getClassAttributes read implemented interfaces attributes?

### ISSUE THREAD

**Issue by xepozz** [spiral/framework#428]
Shouldn't `NativeAttributeReader::getClassAttributes` read implemented interfaces attributes?
https://github.com/spiral/attributes/blob/master/src/Internal/NativeAttributeReader.php#L45

In [this case](https://3v4l.org/5VuOA#v8.0.8) I expect to get all attributes cascade inherited.

**Comment by SerafimArts** [comment]
This feature request does not match the original behavior of the PHP. For reading from parents, you should implement this traversal algorithm yourself.

1) Because in addition to interfaces, there are also traits and parent classes that can be included in any order.
1.1) Moreover, the reading order of the hierarchy is non-deterministic.
2) In the case of absence of a flag `Attribute::IS_REPEATABLE` (unique attribute), this behavior with reading all descendants would violate this restriction.

One of the options for recursive traversal (example of implementation) of all parents using a reader is implemented here: https://github.com/temporalio/sdk-php/blob/master/src/Internal/Declaration/Reader/ActivityReader.php#L76

On the other hand, this is a fairly popular case for reading data, so it might make sense to include a helper class to recursively traverse all parents. It will be necessary to think about this topic.
