### ISSUE TITLE
Attributes: Forward support for dynamic expressions in args?

### ISSUE THREAD

**Issue by donquixote** [spiral/framework#457]
## Description

It looks like future versions of PHP will support dynamic expressions in initializers.
(I am using the term "dynamic" quite loosely here, for anything that is currently not allowed in const expressions)
See https://wiki.php.net/rfc/new_in_initializers. Also have a look at "Future scope".

This means we can have attributes like this:

```php
#[A(new \stdClass)]
class C {}
```

When this happens, we will end up with the following situation:
- nikic/php-parser will likely / hopefully add support for dynamic initializers. Let's say this happens in PHP 8.x.
- In newer versions of PHP 8, NativeAttributeReader will support the new initializers.
- For PHP < 8, FallbackAttributeReader will support the new initializers.
- For PHP >= 8.0, < 8.x, NativeAttributeReader will break with new initializers.

So, should PHP < 8.x use the FallbackAttributeReader, to add forward support for dynamic initializers?

To fully replace annotations with attributes, we will need the option for nested object trees, and this needs dynamic initializers.

For the record, here is a related post that I did on the internals list recently, https://externals.io/message/116181

**Comment by SerafimArts** [comment]
@donquixote yep, we (within the team) discussed this functionality and should be added. I can’t name the exact implementation date.

During the discussion of this problem, we decided that the best option would be to automatically switch drivers from native to fallback in case of syntax errors (via try/catch with choice memoization), since we are not immune from cases when some more syntax will be added in future versions of the PHP.

Moreover, it will be the most convenient option for users, because they don't have to think about changing something in code. And advanced ones (who know what they want) will be able to immediately choose between `NativeAttributeReader` and `FallbackAttributeReader` drivers, using them directly.
